"""Bind section image slots to real files.

Order of preference: imagery extracted from the source site, then imagery
generated by services/image-pipeline (not wired here), then declared
unresolved. A slot is never silently left pointing at placeholder.svg — an
unresolved slot is recorded so a gate can see it and a generation job can
fill it.

Real extraction data (measured against
tenants/cape-crypto/builds/task4-verify/extractions/cape-crypto-9d4fcf88/
extraction-data.json) does NOT carry a top-level `images` list or a
`localPath` field the way an early draft of this module assumed. The real
shape is:

    extraction_data["assets"]["images"]            # {src, alt, sectionIndex, ...}
    extraction_data["assets"]["logos"]              # {url, alt, ...} — note "url" not "src"
    extraction_data["assets"]["backgroundImages"]   # CSS gradients, no file — not resolvable here

Two more real-world wrinkles this module accounts for:

1. Generated section .tsx doesn't only reference images via a literal
   `src="..."` attribute — LOGO-BAR templates put the URL in a JS object
   (`{ image: 'https://...' }`) and pass it through as `src={logo.image}`.
   Matching only `src="..."` would miss every partner-logo strip.
2. The query-string cache-buster on an asset URL (`?v=<hash>`) differs
   between the extraction crawl and whatever later re-crawl or template
   fill produced the section — the same physical asset shows up under two
   different full URLs. Matching must fall back to the URL with its query
   string stripped.
3. extraction-data.json is a SINGLE-PAGE crawl (of the source site's
   homepage), while a multipage build fills sections for every route from
   the site spec. An `/about` section legitimately carries an image URL
   from the source site's /about page that the homepage crawl never saw.
   Requiring a lookup hit before downloading therefore rejects real,
   live, same-origin source imagery — see `_known_hosts`.
4. Template .tsx carries prose documentation, and that documentation
   talks about `src` attributes and asset URLs. Scanning the raw file
   makes a comment that mentions `<Image src="">` register as a real
   unresolved image slot. Scanning must ignore comments — see
   `_mask_comments`.
"""
from __future__ import annotations

import hashlib
import re
import shutil
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

# Matches src="..." / src='...' attributes, including empty ones.
SRC_ATTR_RE = re.compile(r'src=(["\'])(?P<val>[^"\']*)\1')

# Matches any quoted remote image URL anywhere in the tsx — covers both
# JSX attributes and JS object literals (e.g. `image: 'https://...png'`).
IMG_URL_RE = re.compile(
    r'(?P<quote>["\'])(?P<url>https?://[^"\']+?\.(?:png|jpe?g|svg|webp|gif|avif))'
    r'(?P<query>\?[^"\']*)?(?P=quote)',
    re.IGNORECASE,
)

PLACEHOLDERS = {"/placeholder.svg", "/placeholder.jpg", "/placeholder.png", "#", ""}

# Comment spans to blank out before scanning for image references.
#
# Block comments are matched non-greedily so consecutive JSDoc blocks stay
# separate. Line comments require the `//` NOT to be preceded by a colon, so
# the `//` in `https://…` inside a string literal is never mistaken for the
# start of a comment. Deliberately regex-based rather than a full JS
# tokenizer: these templates carry apostrophes in JSX prose ("doesn't"), and
# a state machine that tracked quotes would treat one as an unterminated
# string literal and swallow the rest of the file.
_COMMENT_RE = re.compile(r"/\*.*?\*/|(?<!:)//[^\n]*", re.DOTALL)


def _mask_comments(tsx: str) -> str:
    """Return `tsx` with every comment blanked to spaces, same length.

    Length is preserved so a match found in the masked text sits at the same
    offset as in the original — and so multi-line block comments keep their
    newlines, which the line-comment branch above depends on.

    A template's own documentation discusses the markup it generates: ABOUT
    editorial-split explains that `<Image src="">` throws in next/image. Read
    literally, that comment is an empty src attribute, so every section built
    from that template reported a phantom unresolved image slot — imagery
    that no generator could ever fill because the "slot" is a sentence.
    """
    def blank(m):
        return "".join("\n" if c == "\n" else " " for c in m.group(0))
    return _COMMENT_RE.sub(blank, tsx)

# Some origin servers (confirmed: capecrypto.com) return 403 Forbidden to
# Python's default User-Agent ("Python-urllib/3.x") while serving the same
# asset fine to a browser-like one. Without this header the resolver would
# silently resolve nothing in production — matching would succeed, every
# download would fail, and every slot would be recorded unresolved.
_REQUEST_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    )
}

_IMAGE_MAGIC = (
    (b"\x89PNG\r\n\x1a\n", None),
    (b"\xff\xd8\xff", None),           # JPEG
    (b"GIF87a", None),
    (b"GIF89a", None),
    (b"RIFF", b"WEBP"),                # RIFF....WEBP
    (b"BM", None),                     # BMP, unlikely but cheap to allow
)

# AVIF/HEIC-family: ISO base media file format, brand sits at bytes 8:12
# after a 4-byte box size and the "ftyp" box type at bytes 4:8.
_FTYP_BRANDS = (b"avif", b"avis", b"mif1", b"heic", b"heix")


def _looks_like_image(path: Path) -> bool:
    """Reject downloads that landed on disk but aren't actually image bytes —
    e.g. an HTML 403/error page saved because the caller only checked size."""
    try:
        head = path.read_bytes()[:512]
    except OSError:
        return False
    if not head:
        return False
    for magic, offset_magic in _IMAGE_MAGIC:
        if head.startswith(magic):
            if offset_magic is None:
                return True
            if head[8:12] == offset_magic:
                return True
    if len(head) >= 12 and head[4:8] == b"ftyp" and head[8:12] in _FTYP_BRANDS:
        return True

    # SVG/XML: tolerate a leading BOM, whitespace, and one or more leading
    # XML comments (`<!-- generated by ... -->`) before the real root tag —
    # all three appear in real extracted SVGs and would otherwise
    # false-negative a perfectly good asset into "unresolved".
    text = head.lstrip(b"\xef\xbb\xbf").lstrip()
    for _ in range(4):  # bounded: don't loop forever on adversarial input
        if not text.startswith(b"<!--"):
            break
        end = text.find(b"-->")
        if end == -1:
            break
        text = text[end + 3:].lstrip()
    if text.startswith(b"<svg") or text.startswith(b"<?xml"):
        return True
    return False


class DownloadError(Exception):
    """Raised by `_download` variants that want to report *why* a fetch
    failed (host unreachable vs. HTTP error vs. timeout vs. not-an-image),
    rather than collapsing every failure to a bare 0. `resolve_assets` only
    needs the byte count, but callers diagnosing a resolver that resolves
    nothing (e.g. tests) can call `_download_verbose` directly."""


def _download_verbose(url: str, dest: Path) -> int:
    """Fetch a remote image with a browser-like User-Agent, verify it's
    actually image bytes, and raise DownloadError with the real cause on
    failure instead of swallowing it. Returns bytes written on success."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    request = urllib.request.Request(url, headers=_REQUEST_HEADERS)
    try:
        with urllib.request.urlopen(request, timeout=20) as resp, open(dest, "wb") as out:
            shutil.copyfileobj(resp, out)
    except urllib.error.HTTPError as e:
        if dest.exists():
            dest.unlink()
        raise DownloadError(f"server returned HTTP {e.code}") from e
    except urllib.error.URLError as e:
        if dest.exists():
            dest.unlink()
        raise DownloadError(f"host unreachable ({e.reason})") from e
    except TimeoutError as e:
        if dest.exists():
            dest.unlink()
        raise DownloadError("timed out") from e
    except Exception as e:
        if dest.exists():
            dest.unlink()
        raise DownloadError(f"{type(e).__name__}: {e}") from e

    if not _looks_like_image(dest):
        size = dest.stat().st_size
        dest.unlink()
        raise DownloadError(f"response was not image bytes ({size} bytes written, discarded)")
    return dest.stat().st_size


def _download(url: str, dest: Path) -> int:
    """Fetch a remote image. Returns bytes written, 0 on any failure
    (unreachable host, non-2xx response, or a response that isn't actually
    an image — e.g. a 403 error page saved under an image extension)."""
    try:
        return _download_verbose(url, dest)
    except DownloadError:
        return 0


def _entries(extraction_data: dict) -> list:
    """Flatten every asset record that carries a resolvable URL.

    Reads the real `assets.images` / `assets.logos` structure. Also
    tolerates a top-level `images` (and `logos`) key so synthetic fixtures
    written before this module existed keep working.
    """
    extraction_data = extraction_data or {}
    assets = extraction_data.get("assets") or {}
    entries = []
    entries += assets.get("images") or []
    entries += assets.get("logos") or []
    entries += extraction_data.get("images") or []
    entries += extraction_data.get("logos") or []
    return entries


def _build_lookup(extraction_data: dict) -> dict:
    """Map both the exact URL and the query-stripped URL to its asset record.

    The query-stripped key is what actually resolves real data: the crawl
    that produced extraction-data.json and the template fill that produced
    the section .tsx can carry different cache-buster hashes for the same
    file.
    """
    lookup = {}
    for entry in _entries(extraction_data):
        url = entry.get("src") or entry.get("url")
        if not url:
            continue
        bare = url.split("?", 1)[0]
        lookup.setdefault(url, entry)
        lookup.setdefault(bare, entry)
    return lookup


def _known_hosts(extraction_data: dict) -> set:
    """Hosts the extraction crawl actually served assets from.

    extraction-data.json is a crawl of ONE page (the source homepage), but a
    multipage build fills sections for every route from the site spec, and
    those fills carry image URLs the homepage crawl never recorded — the real
    Cape Crypto /about sections reference `/content/images/…/dave.webp` and
    `leon-portrait.webp`, both live and fetchable, neither in the crawl.
    Gating the download on a lookup hit declared them unresolved and left the
    remote URL in the shipped .tsx, so the deployed site hotlinked the source
    origin for an image it was supposed to own.

    A URL on a host the crawl already vouched for is source imagery whether or
    not this particular crawl page happened to reference it. Anything on any
    other host is still refused: this widens the resolver from one page of the
    source site to the whole source site, not to the open internet.
    """
    hosts = set()
    for entry in _entries(extraction_data):
        url = entry.get("src") or entry.get("url")
        if not url:
            continue
        host = urllib.parse.urlsplit(url).netloc.lower()
        if host:
            hosts.add(host)
    return hosts


def _local_rel_path(canonical_url: str) -> str:
    """Derive a collision-free, cache-stable local path for a source URL.

    Two distinct source URLs must never produce the same local filename —
    `logo.png` under `/assets/partners/` and under `/content/brand/` are a
    realistic collision on a real site, and a basename-only filename would
    silently make the second one adopt the first one's downloaded bytes.
    The same source URL must always produce the same local filename so the
    on-disk cache (`dest.exists()`) still works run over run.

    Hashing the full query-stripped URL (not just the basename) satisfies
    both: distinct paths hash distinctly, and a stable path hashes
    identically across repeated resolutions.
    """
    bare = canonical_url.split("?", 1)[0]
    stem = Path(bare).stem or "asset"
    suffix = Path(bare).suffix or ""
    digest = hashlib.sha1(bare.encode("utf-8")).hexdigest()[:10]
    # Keep the readable stem for debuggability, but the hash is what
    # guarantees uniqueness — sanitize the stem defensively since it comes
    # from an untrusted remote URL path.
    safe_stem = re.sub(r"[^A-Za-z0-9._-]", "-", stem)[:60] or "asset"
    return f"images/{safe_stem}-{digest}{suffix}"


def _images_for_section(extraction_data: dict, section_index) -> list:
    """Extracted images tagged with a given sectionIndex, images only (logos
    aren't section-scoped in the real data — their sectionIndex is null)."""
    if section_index is None:
        return []
    assets = (extraction_data or {}).get("assets") or {}
    return [
        img for img in (assets.get("images") or [])
        if img.get("sectionIndex") == section_index and (img.get("src"))
    ]


def resolve_assets(artifact, extraction_data: dict, public_dir: Path,
                    section_index=None, download_fn=_download):
    """Rewrite image srcs to local paths, recording each outcome.

    `section_index` is the extraction-crawl section index this artifact was
    built from (see `assets.images[].sectionIndex` in extraction-data.json).
    When given, it is used to opportunistically fill a bare placeholder slot
    (`/placeholder.svg`, `""`, `#`) from an extracted image known to belong
    to that same section — never from an arbitrary/unrelated image, and
    never with generated/fabricated content. Without a matching extracted
    image the slot is recorded unresolved, not silently placeheld.
    """
    lookup = _build_lookup(extraction_data)
    known_hosts = _known_hosts(extraction_data)
    section_pool = _images_for_section(extraction_data, section_index)
    used_section_srcs = set()
    tsx = artifact.tsx
    assets = list(artifact.assets)

    def _resolve_and_download(fetch_url: str, canonical_url: str):
        """Try to materialize `fetch_url` under public_dir, named
        deterministically from `canonical_url` (the extraction record's own
        URL — stable across cache-buster query drift). Two distinct source
        URLs never collide on the local filename; the same source URL always
        maps to the same local filename so the on-disk cache is safe to
        reuse. A cached file is only trusted if it is non-empty and still
        looks like real image bytes — a zero-byte or non-image leftover from
        an earlier failed run is redownloaded, not adopted.
        Returns (local_src, bytes) or None.
        """
        local_rel = _local_rel_path(canonical_url)
        dest = public_dir / local_rel
        if dest.exists() and dest.stat().st_size > 0 and _looks_like_image(dest):
            size = dest.stat().st_size
        else:
            size = download_fn(fetch_url, dest)
        if size > 0:
            return "/" + local_rel.lstrip("/"), size
        return None

    # Both passes scan the comment-masked text, never the raw .tsx: a
    # template's documentation talks about `src` attributes and asset URLs,
    # and matching it invents image slots that no generator can fill. Only
    # the SCAN uses the mask — every rewrite below still targets `tsx`, so
    # the emitted file keeps its comments intact.
    scan = _mask_comments(tsx)

    # Pass 1: remote image URLs already referenced in the tsx (attribute or
    # JS object literal), matched against extraction data by exact-or-
    # query-stripped URL, or accepted as same-origin source imagery the
    # single-page crawl simply didn't see.
    seen = set()
    for m in IMG_URL_RE.finditer(scan):
        full_url = m.group("url") + (m.group("query") or "")
        if full_url in seen:
            continue
        seen.add(full_url)
        bare_url = m.group("url")

        match = lookup.get(full_url) or lookup.get(bare_url)
        resolved = None
        if match:
            canonical_url = match.get("src") or match.get("url") or bare_url
            resolved = _resolve_and_download(full_url, canonical_url)
        elif urllib.parse.urlsplit(bare_url).netloc.lower() in known_hosts:
            # Same source site, different page than the one crawled. The
            # query-stripped URL is the canonical name here — there is no
            # extraction record to take one from.
            resolved = _resolve_and_download(full_url, bare_url)
        if resolved:
            local_src, size = resolved
            tsx = tsx.replace(full_url, local_src)
            assets.append({"slot": "image", "src": local_src, "origin": "extracted", "bytes": size})
        else:
            assets.append({"slot": "image", "src": full_url, "origin": "unresolved", "bytes": 0})

    # Pass 2: bare src="" / placeholder slots. Try a section-scoped
    # extracted image first; otherwise declare the gap.
    for _, val in SRC_ATTR_RE.findall(scan):
        if val not in PLACEHOLDERS:
            continue  # either already local-and-real, or handled in pass 1

        filled = False
        for candidate in section_pool:
            src = candidate["src"]
            if src in used_section_srcs:
                continue
            resolved = _resolve_and_download(src, src)
            if resolved:
                local_src, size = resolved
                used_section_srcs.add(src)
                # Replace exactly one occurrence of this placeholder attribute,
                # trying both quote styles.
                before = tsx
                tsx = tsx.replace(f'src="{val}"', f'src="{local_src}"', 1)
                if tsx == before:
                    tsx = tsx.replace(f"src='{val}'", f"src='{local_src}'", 1)
                assets.append({"slot": "image", "src": local_src, "origin": "extracted", "bytes": size})
                filled = True
                break
        if not filled:
            assets.append({"slot": "image", "src": val, "origin": "unresolved", "bytes": 0})

    artifact.tsx = tsx
    artifact.assets = assets
    return artifact


def gaps(artifact) -> list:
    """Unresolved image slots, shaped as image-pipeline job inputs."""
    return [
        {
            "section_uid": artifact.section_uid,
            "archetype": artifact.archetype,
            "variant": artifact.variant,
            "slot": a["slot"],
            "reason": "no extracted source",
        }
        for a in artifact.assets
        if a["origin"] == "unresolved"
    ]
