"""Bind section image slots to real files.

Order of preference: imagery extracted from the source site, then imagery
generated by services/image-pipeline (not wired here), then declared
unresolved. A slot is never silently left pointing at placeholder.svg — an
unresolved slot is recorded so a gate can see it and a generation job can
fill it.

Real extraction data (measured against
tenants/cape-crypto/builds/task4-verify/extractions/cape-crypto-9d4fcf88/
extraction-data.json) does NOT carry a top-level `images` list or a
`localPath` field the way an early draft of this module assumed. The real
shape is:

    extraction_data["assets"]["images"]            # {src, alt, sectionIndex, ...}
    extraction_data["assets"]["logos"]              # {url, alt, ...} — note "url" not "src"
    extraction_data["assets"]["backgroundImages"]   # CSS gradients, no file — not resolvable here

Two more real-world wrinkles this module accounts for:

1. Generated section .tsx doesn't only reference images via a literal
   `src="..."` attribute — LOGO-BAR templates put the URL in a JS object
   (`{ image: 'https://...' }`) and pass it through as `src={logo.image}`.
   Matching only `src="..."` would miss every partner-logo strip.
2. The query-string cache-buster on an asset URL (`?v=<hash>`) differs
   between the extraction crawl and whatever later re-crawl or template
   fill produced the section — the same physical asset shows up under two
   different full URLs. Matching must fall back to the URL with its query
   string stripped.
"""
from __future__ import annotations

import re
import shutil
import urllib.request
from pathlib import Path

# Matches src="..." / src='...' attributes, including empty ones.
SRC_ATTR_RE = re.compile(r'src=(["\'])(?P<val>[^"\']*)\1')

# Matches any quoted remote image URL anywhere in the tsx — covers both
# JSX attributes and JS object literals (e.g. `image: 'https://...png'`).
IMG_URL_RE = re.compile(
    r'(?P<quote>["\'])(?P<url>https?://[^"\']+?\.(?:png|jpe?g|svg|webp|gif|avif))'
    r'(?P<query>\?[^"\']*)?(?P=quote)',
    re.IGNORECASE,
)

PLACEHOLDERS = {"/placeholder.svg", "/placeholder.jpg", "/placeholder.png", "#", ""}


def _download(url: str, dest: Path) -> int:
    """Fetch a remote image. Returns bytes written, 0 on failure."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        with urllib.request.urlopen(url, timeout=20) as resp, open(dest, "wb") as out:
            shutil.copyfileobj(resp, out)
        return dest.stat().st_size
    except Exception:
        if dest.exists():
            dest.unlink()
        return 0


def _entries(extraction_data: dict) -> list:
    """Flatten every asset record that carries a resolvable URL.

    Reads the real `assets.images` / `assets.logos` structure. Also
    tolerates a top-level `images` (and `logos`) key so synthetic fixtures
    written before this module existed keep working.
    """
    extraction_data = extraction_data or {}
    assets = extraction_data.get("assets") or {}
    entries = []
    entries += assets.get("images") or []
    entries += assets.get("logos") or []
    entries += extraction_data.get("images") or []
    entries += extraction_data.get("logos") or []
    return entries


def _build_lookup(extraction_data: dict) -> dict:
    """Map both the exact URL and the query-stripped URL to its asset record.

    The query-stripped key is what actually resolves real data: the crawl
    that produced extraction-data.json and the template fill that produced
    the section .tsx can carry different cache-buster hashes for the same
    file.
    """
    lookup = {}
    for entry in _entries(extraction_data):
        url = entry.get("src") or entry.get("url")
        if not url:
            continue
        bare = url.split("?", 1)[0]
        lookup.setdefault(url, entry)
        lookup.setdefault(bare, entry)
    return lookup


def _images_for_section(extraction_data: dict, section_index) -> list:
    """Extracted images tagged with a given sectionIndex, images only (logos
    aren't section-scoped in the real data — their sectionIndex is null)."""
    if section_index is None:
        return []
    assets = (extraction_data or {}).get("assets") or {}
    return [
        img for img in (assets.get("images") or [])
        if img.get("sectionIndex") == section_index and (img.get("src"))
    ]


def resolve_assets(artifact, extraction_data: dict, public_dir: Path,
                    section_index=None, download_fn=_download):
    """Rewrite image srcs to local paths, recording each outcome.

    `section_index` is the extraction-crawl section index this artifact was
    built from (see `assets.images[].sectionIndex` in extraction-data.json).
    When given, it is used to opportunistically fill a bare placeholder slot
    (`/placeholder.svg`, `""`, `#`) from an extracted image known to belong
    to that same section — never from an arbitrary/unrelated image, and
    never with generated/fabricated content. Without a matching extracted
    image the slot is recorded unresolved, not silently placeheld.
    """
    lookup = _build_lookup(extraction_data)
    section_pool = _images_for_section(extraction_data, section_index)
    used_section_srcs = set()
    tsx = artifact.tsx
    assets = list(artifact.assets)

    def _resolve_and_download(url: str):
        """Try to materialize `url` under public_dir. Returns (local_src, bytes) or None."""
        bare = url.split("?", 1)[0]
        local_rel = "images/" + Path(bare).name
        dest = public_dir / local_rel
        size = dest.stat().st_size if dest.exists() else download_fn(url, dest)
        if size > 0:
            return "/" + local_rel.lstrip("/"), size
        return None

    # Pass 1: remote image URLs already referenced in the tsx (attribute or
    # JS object literal), matched against extraction data by exact-or-
    # query-stripped URL.
    seen = set()
    for m in IMG_URL_RE.finditer(tsx):
        full_url = m.group("url") + (m.group("query") or "")
        if full_url in seen:
            continue
        seen.add(full_url)
        bare_url = m.group("url")

        match = lookup.get(full_url) or lookup.get(bare_url)
        resolved = None
        if match:
            resolved = _resolve_and_download(full_url)
        if resolved:
            local_src, size = resolved
            tsx = tsx.replace(full_url, local_src)
            assets.append({"slot": "image", "src": local_src, "origin": "extracted", "bytes": size})
        else:
            assets.append({"slot": "image", "src": full_url, "origin": "unresolved", "bytes": 0})

    # Pass 2: bare src="" / placeholder slots. Try a section-scoped
    # extracted image first; otherwise declare the gap.
    for _, val in SRC_ATTR_RE.findall(tsx):
        if val not in PLACEHOLDERS:
            continue  # either already local-and-real, or handled in pass 1

        filled = False
        for candidate in section_pool:
            src = candidate["src"]
            if src in used_section_srcs:
                continue
            resolved = _resolve_and_download(src)
            if resolved:
                local_src, size = resolved
                used_section_srcs.add(src)
                # Replace exactly one occurrence of this placeholder attribute,
                # trying both quote styles.
                before = tsx
                tsx = tsx.replace(f'src="{val}"', f'src="{local_src}"', 1)
                if tsx == before:
                    tsx = tsx.replace(f"src='{val}'", f"src='{local_src}'", 1)
                assets.append({"slot": "image", "src": local_src, "origin": "extracted", "bytes": size})
                filled = True
                break
        if not filled:
            assets.append({"slot": "image", "src": val, "origin": "unresolved", "bytes": 0})

    artifact.tsx = tsx
    artifact.assets = assets
    return artifact


def gaps(artifact) -> list:
    """Unresolved image slots, shaped as image-pipeline job inputs."""
    return [
        {
            "section_uid": artifact.section_uid,
            "archetype": artifact.archetype,
            "variant": artifact.variant,
            "slot": a["slot"],
            "reason": "no extracted source",
        }
        for a in artifact.assets
        if a["origin"] == "unresolved"
    ]
