"""Lower an art gap to a `job-v1` spec for services/image-pipeline.

`services/image-pipeline` is a complete deterministic creative compiler with a
Higgsfield adapter and, until now, no caller. This module is the lowering: an
art gap (`asset_resolver.art_demand`) plus the tenant's brand becomes a job spec
that validates against the REAL schema at
`services/image-pipeline/core/job.schema.json` — read, not summarised, because
the schema sets `additionalProperties: false` on every object and a field
invented from a plan's prose fails validation at the far end of a spend.

Two rules govern everything here.

**Nothing is generated by this module.** It emits a spec. Generation is out of
band (Task M3), cost-estimated first, and the build only ever consumes cache.

**`job_hash` is both the cache key and the determinism guarantee.** It is a
digest of the canonical JSON of the whole job — sorted keys, no builtin `hash()`
anywhere near it (capture filenames already learned that lesson: Python's
`hash()` is salted per process, so a "stable" name changed every run). Same
declaration + same brand ⇒ same hash ⇒ never regenerated and never re-billed.
Change the declaration or the palette and the hash moves, because the picture
should.
"""
from __future__ import annotations

import hashlib
import json
import re

SCHEMA_VERSION = "job-v1"

#: Text-to-image by default. `nano_banana_2` is image-conditioned and is what a
#: job with a look anchor wants; `recraft_v4_1` is the text-to-image model and
#: is the only one of the two the adapter will pass `--colors` to meaningfully.
#: Both names come from the adapter's own docstring, not from memory.
ENGINE_NAME = "higgsfield"
MODEL_TEXT_TO_IMAGE = "recraft_v4_1"
MODEL_WITH_REFERENCE = "nano_banana_2"

_ID_SAFE_RE = re.compile(r"[^a-z0-9]+")

#: What each declared intent asks the engine to compose. Fixed strings, not
#: prose generated per job: the prompt is build output and must be
#: byte-identical run to run.
_COMPOSITION = {
    "abstract": "abstract composition of layered geometric form, generous negative "
                "space, no subject at the centre",
    "scene": "wide environmental scene, natural light, no foreground subject, "
             "horizon low in frame",
    "texture": "flat full-bleed material texture, even illumination, no focal "
               "point, tiles without a visible seam",
    "diagram": "flat schematic composition of simple unlabelled shapes and "
               "connectors, generous margins",
    "product": "unreachable — a generated product depiction is refused",
}

#: The prohibitions, carried INTO the prompt rather than left to the reviewer.
#: `asset_resolver.claim_bearing_reason()` refuses a claim-bearing DECLARATION;
#: this is the second line, against a permissible declaration whose generation
#: drifts into a claim anyway. Cape Crypto is an FSCA-licensed FSP (No. 53746):
#: an invented percentage in a corner of a texture is a regulatory liability,
#: not a rendering artefact.
NEGATIVE_PROMPT = (
    "text, words, letters, numbers, percentages, currency symbols, price tags, "
    "charts, graphs, candlestick charts, tickers, dashboards, user interfaces, "
    "screenshots, phone or laptop screens, logos, wordmarks, badges, seals, "
    "certificates, medals, award ribbons, people, faces, hands, portraits, "
    "watermarks, signatures"
)


class ClaimBearingJob(Exception):
    """Raised when a gap that must never be generated reaches the lowering.

    `asset_resolver` already refuses these before they become gaps. This is the
    second gate on the same rule, on the theory that the boundary should hold
    even if a future caller builds a gap by hand.
    """


def _slug(*parts) -> str:
    """A `^[a-z0-9][a-z0-9-]*$` id fragment. The schema enforces the pattern;
    a job whose id fails it is rejected before any spend, which is the right
    direction but a poor time to find out."""
    raw = "-".join(str(p) for p in parts if p)
    out = _ID_SAFE_RE.sub("-", raw.lower()).strip("-")
    return out or "job"


def _palette(brand: dict) -> list:
    """Brand hexes, in a fixed order, deduplicated, only real hex values.

    Order is fixed rather than sorted so the palette reads accent-first to the
    engine, and fixed order is equally deterministic.
    """
    seen, out = set(), []
    for key in ("accent", "background", "foreground", "surface", "surface_inverse"):
        val = (brand or {}).get(key)
        if not isinstance(val, str):
            continue
        val = val.strip().lower()
        if not re.fullmatch(r"#[0-9a-f]{3,8}", val) or val in seen:
            continue
        seen.add(val)
        out.append(val)
    return out


def _reference(brand: dict):
    """The look anchor: the benchmark's OWN captured imagery.

    This is the field that keeps a commissioned picture in the same visual
    language as the reference the design was compiled from, rather than in
    whatever house style the model defaults to. Marked `optional` so a missing
    capture is a warning at run time, not a hard failure — an offline or
    unfunded run must degrade to "this slot is empty and named".
    """
    refs = (brand or {}).get("reference_images") or []
    refs = [r for r in refs if isinstance(r, str) and r.strip()]
    if not refs:
        return None
    return [{"image": r, "optional": True} for r in refs]


def to_job_v1(gap: dict, brand: dict) -> dict:
    """An art gap + a brand → one `job-v1` spec.

    `gap` is a row from `asset_resolver.art_demand()`:
    `{section_uid, archetype, variant, slot, intent, aspect, role, reason}`.

    `brand` carries the tenant's compiled palette and identity — the same
    values phase 0 declares and the design compiler emits as tokens:
    `{name, accent, background, foreground, reference_images: [...]}`.
    """
    intent = (gap.get("intent") or "").lower()
    if intent == "product":
        raise ClaimBearingJob(
            "intent 'product': a generated product depiction is a claim about a "
            "real product"
        )
    if intent not in _COMPOSITION:
        raise ValueError("unknown art intent %r" % intent)

    brand = brand or {}
    brand_name = str(brand.get("name") or "").strip()
    colors = _palette(brand)
    background = (
        "ground derived from the brand palette (%s), unbroken, no vignette"
        % ", ".join(colors)
        if colors else
        "unbroken neutral ground, no vignette"
    )
    composition = _COMPOSITION[intent]

    subject = {
        "brand_name": brand_name or "the brand",
        "intent": intent,
        "archetype": gap.get("archetype") or "",
        "variant": gap.get("variant") or "",
        "slot": gap.get("slot") or "",
        "role": gap.get("role") or "decorative",
    }

    # Placeholders resolve from `subject` plus the two output fields the
    # pipeline folds in ({composition}, {background}). Every name used below is
    # present in one of those, so no placeholder can survive into the prompt.
    prompt = (
        "Non-representational {intent} artwork for the {archetype} section of "
        "{brand_name}'s website. {composition}. {background}. "
        "Calm, precise, editorial; suitable as a quiet backdrop behind text. "
        "It must depict no people, no products, no interfaces, no documents and "
        "no data of any kind."
    )

    reference = _reference(brand)
    job = {
        "schema_version": SCHEMA_VERSION,
        "id": _slug(gap.get("archetype"), gap.get("variant"), gap.get("slot"),
                    gap.get("section_uid")),
        "subject": subject,
        "spec": {
            "prompt_template": prompt,
            "negative": NEGATIVE_PROMPT,
        },
        "output": {
            "imgtype": _slug(gap.get("archetype"), gap.get("slot")),
            "aspect_ratio": gap.get("aspect") or "16:9",
            "resolution": "2k",
            "count": 1,
            "background": background,
            "composition": composition,
        },
        "engine": {
            "name": ENGINE_NAME,
            "model": MODEL_WITH_REFERENCE if reference else MODEL_TEXT_TO_IMAGE,
        },
    }
    if colors:
        job["output"]["colors"] = colors
    if reference is not None:
        job["reference"] = reference
    if not reference:
        job["engine"]["model_type"] = "standard"
    return job


def canonical_json(job: dict) -> str:
    """The exact bytes the hash is taken over. Sorted keys, no incidental
    whitespace, UTF-8 preserved — so two processes, two machines and two
    Python versions agree."""
    return json.dumps(job, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


#: Job fields that identify WHICH SECTION asked, not WHAT PICTURE was asked for.
#: Excluded from the hash — see `job_hash`.
_HASH_EXCLUDED_KEYS = ("id",)


def cache_key_json(job: dict) -> str:
    """`canonical_json` of the picture-determining part of a job.

    `id` carries the demanding section's `section_uid` so a generated file can
    be traced back to the artifact that asked for it. That is worth keeping —
    but it must not reach the hash, or two sections making the SAME request
    become two cache entries and two charges.

    Measured on cape-crypto: five HERO | centered sections each declare
    `slot=backdrop_url intent=texture aspect=16:9`. With `id` in the digest
    that is five hashes for five byte-identical prompts — five generations
    billed for one picture, in a module whose docstring promises the opposite.
    Excluding `id` collapses them to one.
    """
    return canonical_json({k: v for k, v in job.items()
                           if k not in _HASH_EXCLUDED_KEYS})


def job_hash(job: dict) -> str:
    """Content hash of a job spec — the cache key AND the determinism claim.

    SHA-256 over `cache_key_json`, truncated to 16 hex characters (64 bits;
    collision-implausible for a corpus of tens of jobs per tenant, and short
    enough to be a readable filename).

    Same declaration + same brand ⇒ same hash, WHEREVER it was declared ⇒
    generated once, cached, reused. Change the declaration or the palette and
    the hash moves, because the picture should.

    NEVER Python's builtin `hash()`: it is salted per process, so the same job
    would key a different cache entry every run and every generation would be
    re-billed. The capture filenames in this repo already shipped that bug once.
    """
    return hashlib.sha256(cache_key_json(job).encode("utf-8")).hexdigest()[:16]
