"""Lower an art gap to a `job-v1` spec for services/image-pipeline.

`services/image-pipeline` is a complete deterministic creative compiler with a
Higgsfield adapter and, until now, no caller. This module is the lowering: an
art gap (`asset_resolver.art_demand`) plus the tenant's brand becomes a job spec
that validates against the REAL schema at
`services/image-pipeline/core/job.schema.json` — read, not summarised, because
the schema sets `additionalProperties: false` on every object and a field
invented from a plan's prose fails validation at the far end of a spend.

Two rules govern everything here.

**Nothing is generated by this module.** It emits a spec. Generation is out of
band (Task M3), cost-estimated first, and the build only ever consumes cache.

**`job_hash` is both the cache key and the determinism guarantee.** It is a
digest of the canonical JSON of the whole job — sorted keys, no builtin `hash()`
anywhere near it (capture filenames already learned that lesson: Python's
`hash()` is salted per process, so a "stable" name changed every run). Same
declaration + same brand ⇒ same hash ⇒ never regenerated and never re-billed.
Change the declaration or the palette and the hash moves, because the picture
should.
"""
from __future__ import annotations

import hashlib
import json
import re

SCHEMA_VERSION = "job-v1"

#: The version a job carrying motion declares. `job-v1` is still accepted by the
#: schema verbatim — v2 only ADDS `media_type` and the `motion`/`remotion`
#: objects — so an image job is left at v1 rather than bumped. Nothing is gained
#: by rewriting artefacts that are already valid, and a rewritten artefact is a
#: changed hash.
SCHEMA_VERSION_MOTION = "job-v2"

MEDIA_TYPE_IMAGE = "image"
MEDIA_TYPE_VIDEO = "video"
MEDIA_TYPES = (MEDIA_TYPE_IMAGE, MEDIA_TYPE_VIDEO)

#: The two motion engines, and the policy between them, from
#: `docs/census/2026-08-17-motion-engine.md` §2: Remotion is canonical for the
#: deterministic UI/product class (77% of the reference's distinct pieces);
#: generation serves atmospheric backdrops only.
ENGINE_REMOTION = "remotion"
ENGINE_GENERATIVE = "generative"

#: What an atmospheric backdrop is, expressed in the vocabulary this repo
#: already has (`asset_resolver.VALID_ART_INTENTS` / `VALID_ART_ROLES`) rather
#: than in a new taxonomy. All four atmospheric pieces in the reference are
#: unbroken gradient fields sitting behind an overlay — decorative, and either
#: `texture` or `abstract`. A `scene`, a `diagram` or a load-bearing slot is a
#: piece a viewer reads for information, and a non-deterministic generator must
#: not be the thing that renders it.
_ATMOSPHERIC_INTENTS = ("abstract", "texture")
_ATMOSPHERIC_ROLE = "decorative"

#: The provenance sources a rendered frame may carry. `default` is absent
#: deliberately — the same rule `SectionArtifact.validate()` enforces for copy.
#: A string burned into a video frame is no less of a claim for being pixels.
VALID_PROPS_SOURCES = ("harvested", "phase0")

MOTION_CONTAINERS = ("mp4", "webm", "png-sequence")

#: Text-to-image by default. `nano_banana_2` is image-conditioned and is what a
#: job with a look anchor wants; `recraft_v4_1` is the text-to-image model and
#: is the only one of the two the adapter will pass `--colors` to meaningfully.
#: Both names come from the adapter's own docstring, not from memory.
ENGINE_NAME = "higgsfield"
MODEL_TEXT_TO_IMAGE = "recraft_v4_1"
MODEL_WITH_REFERENCE = "nano_banana_2"

_ID_SAFE_RE = re.compile(r"[^a-z0-9]+")

#: What each declared intent asks the engine to compose. Fixed strings, not
#: prose generated per job: the prompt is build output and must be
#: byte-identical run to run.
_COMPOSITION = {
    "abstract": "abstract composition of layered geometric form, generous negative "
                "space, no subject at the centre",
    # NOT "wide": the aspect ratio is DECLARED per slot and the only `scene`
    # demand on this site is 4:5 portrait. A prompt that says "wide" while the
    # engine is handed `--aspect_ratio 4:5` asks for two different pictures and
    # gets the worse of both.
    "scene": "environmental scene with real depth — landscape or architecture, "
             "natural directional light, no foreground subject",
    # Rewritten after looking at what the first version bought. "flat
    # full-bleed material texture ... tiles without a visible seam" produced a
    # dense blue-and-white CHECKERBOARD: "tiles" was read as an instruction to
    # draw tiles, and "even illumination, no focal point" as an instruction to
    # fill every pixel equally. The result was maximum visual noise behind a
    # headline — the exact opposite of the declared `decorative` role. The
    # word "tile" is gone and the anti-pattern is now stated positively AND
    # negatively, because a generator will happily satisfy a description of
    # what to avoid by drawing it.
    "texture": "an almost-empty field of soft continuous tonal gradation with "
               "fine photographic grain, one broad diffuse band of light "
               "crossing it, and large areas of near-flat ground; no repeating "
               "motif, no grid, no checkerboard, no mosaic, no tiles, no cells, "
               "no geometric shapes, nothing that reads as a pattern",
    "diagram": "flat schematic composition of simple unlabelled shapes and "
               "connectors, generous margins",
    "product": "unreachable — a generated product depiction is refused",
}

#: How the picture opens. Split out of the prompt because ONE lead sentence
#: cannot serve every intent: "Non-representational scene artwork" is a
#: contradiction, and it was what this module asked for until the first real
#: job set was read before spending. A `scene` is representational by
#: definition; what keeps it claim-free is that it depicts no people, no
#: signage and no product — which the negative prompt and the sentence below
#: both say outright.
_LEAD = {
    "abstract": "Non-representational abstract artwork",
    "texture": "Non-representational material texture",
    "diagram": "Non-representational schematic artwork",
    "scene": "A photographic environmental scene, unpeopled and without signage",
    "product": "unreachable — a generated product depiction is refused",
}

#: What the picture has to DO on the page, which the template declares as
#: `role`. A decorative backdrop sits behind text and must recede; a
#: load-bearing image is the subject of its own frame beside body copy. Asking
#: for "a quiet backdrop" in the second case produces exactly the washed-out
#: filler this system is trying to stop shipping.
_USAGE = {
    # "no element competing with a headline" was not specific enough. The first
    # backdrop that satisfied it put its tonal mass through the middle of the
    # frame, and `object-cover` on a wide hero cropped that mass to exactly the
    # band where the muted subheadline sits — legible at the left, fighting the
    # ground by the right edge, on all five pages. The contrast fact-check
    # cannot see it: it measures the token pair, not the composited image. So
    # the constraint is now spatial, which is the thing that was actually
    # wrong, and it is expressed in terms `object-cover` cannot undo — a clear
    # middle survives any centre crop.
    "decorative": "It sits behind text and must recede: low contrast, no "
                  "element competing with a headline. Keep the middle of the "
                  "frame — the full horizontal band through its centre — "
                  "near-empty and near-flat; what tonal mass there is belongs "
                  "in the outer margins, strongest at the corners and fading "
                  "out well before the centre. Place it asymmetrically — two "
                  "corners weighted, the others barely touched — and never as "
                  "a band or bar running the full width or height, which reads "
                  "as a vignette rather than as a composition.",
    "load-bearing": "It stands in its own frame beside body copy and must hold "
                    "attention on its own: a clear focal structure, full "
                    "tonal range.",
}

#: The prohibitions, carried INTO the prompt rather than left to the reviewer.
#: `asset_resolver.claim_bearing_reason()` refuses a claim-bearing DECLARATION;
#: this is the second line, against a permissible declaration whose generation
#: drifts into a claim anyway. Cape Crypto is an FSCA-licensed FSP (No. 53746):
#: an invented percentage in a corner of a texture is a regulatory liability,
#: not a rendering artefact.
NEGATIVE_PROMPT = (
    "text, words, letters, numbers, percentages, currency symbols, price tags, "
    "charts, graphs, candlestick charts, tickers, dashboards, user interfaces, "
    "screenshots, phone or laptop screens, logos, wordmarks, badges, seals, "
    "certificates, medals, award ribbons, people, faces, hands, portraits, "
    "watermarks, signatures"
)


class UncompiledStyle(Exception):
    """Raised when a brand is asked for from a style that has no design
    authority behind it.

    The alternative — falling back to a default palette, or to whatever the
    crawl produced — is the failure this whole module exists downstream of. A
    picture generated against the source site's colours clashes with the page
    the design compiler actually renders, and it costs money to find out. An
    unmeasured design system must read as unmeasured: no jobs, a recorded
    reason, and slots that stay empty and named.
    """


class ClaimBearingJob(Exception):
    """Raised when a gap that must never be generated reaches the lowering.

    `asset_resolver` already refuses these before they become gaps. This is the
    second gate on the same rule, on the theory that the boundary should hold
    even if a future caller builds a gap by hand.
    """


class EnginePolicyViolation(Exception):
    """Raised when a motion demand asks the wrong engine for its class.

    The engine choice is not a preference; it is the finding of the motion
    census, and 77% of the reference's distinct pieces are text-bearing product
    demonstrations. A generative model cannot be relied on to render a specified
    string, and for an FSCA-licensed FSP a misrendered product name in a video is
    a compliance defect. So the boundary lives in code: generation is reachable
    for an atmospheric backdrop and unreachable for anything a viewer reads.
    """


class PropsNotMeasured(Exception):
    """Raised when compiled props are absent, unsourced, or carry no tokens.

    Motion must not claim to read the page's design system when the page has not
    been compiled, and must not render a string whose provenance is unknown. The
    refusal mirrors `motion/tools/build_props.py`, which raises rather than
    defaulting for exactly the same three cases — an unreachable declaration, no
    usable declared content, and absent tokens.
    """


def _slug(*parts) -> str:
    """A `^[a-z0-9][a-z0-9-]*$` id fragment. The schema enforces the pattern;
    a job whose id fails it is rejected before any spend, which is the right
    direction but a poor time to find out."""
    raw = "-".join(str(p) for p in parts if p)
    out = _ID_SAFE_RE.sub("-", raw.lower()).strip("-")
    return out or "job"


#: Which palette roles a job's colour hint carries, and IN WHAT ORDER, by the
#: declared role of the slot.
#:
#: recraft treats `--colors` as a weighted hint and leans on the ones it is
#: given first. The first HERO backdrop was handed accent-then-ground-then-the
#: two dark tones and came back as saturated navy against pure white at maximum
#: separation — unusable behind a headline, whatever the composition asked for.
#:
#: A decorative slot therefore leads with the ground and the tinted surface and
#: drops the two DARK roles entirely; the accent stays last, present but not
#: dominant. It stays because dropping it would also drop the property that a
#: changed accent moves the hash — the design system has to be able to
#: invalidate this picture, and a colour the job never mentions cannot.
_PALETTE_KEYS_BY_ROLE = {
    "decorative": ("background", "surface", "accent"),
    "load-bearing": ("accent", "background", "foreground", "surface",
                     "surface_inverse"),
}


def _palette(brand: dict, role: str = "load-bearing") -> list:
    """Brand hexes, in a fixed order, deduplicated, only real hex values.

    Order is fixed rather than sorted so the palette reads accent-first to the
    engine, and fixed order is equally deterministic.
    """
    seen, out = set(), []
    for key in _PALETTE_KEYS_BY_ROLE.get(role, _PALETTE_KEYS_BY_ROLE["load-bearing"]):
        val = (brand or {}).get(key)
        if not isinstance(val, str):
            continue
        val = val.strip().lower()
        if not re.fullmatch(r"#[0-9a-f]{3,8}", val) or val in seen:
            continue
        seen.add(val)
        out.append(val)
    return out


def _reference(brand: dict):
    """The look anchor: the benchmark's OWN captured imagery.

    This is the field that keeps a commissioned picture in the same visual
    language as the reference the design was compiled from, rather than in
    whatever house style the model defaults to. Marked `optional` so a missing
    capture is a warning at run time, not a hard failure — an offline or
    unfunded run must degrade to "this slot is empty and named".
    """
    refs = (brand or {}).get("reference_images") or []
    refs = [r for r in refs if isinstance(r, str) and r.strip()]
    if not refs:
        return None
    return [{"image": r, "optional": True} for r in refs]


def to_job_v1(gap: dict, brand: dict) -> dict:
    """An art gap + a brand → one `job-v1` spec.

    `gap` is a row from `asset_resolver.art_demand()`:
    `{section_uid, archetype, variant, slot, intent, aspect, role, reason}`.

    `brand` carries the tenant's compiled palette and identity — the same
    values phase 0 declares and the design compiler emits as tokens:
    `{name, accent, background, foreground, reference_images: [...]}`.
    """
    intent = (gap.get("intent") or "").lower()
    if intent == "product":
        raise ClaimBearingJob(
            "intent 'product': a generated product depiction is a claim about a "
            "real product"
        )
    if intent not in _COMPOSITION:
        raise ValueError("unknown art intent %r" % intent)

    role = (gap.get("role") or "decorative").lower()
    brand = brand or {}
    brand_name = str(brand.get("name") or "").strip()
    colors = _palette(brand, role=role)
    if not colors:
        background = "unbroken neutral ground, no vignette"
    elif role == "decorative":
        background = (
            "ground derived from the brand palette (%s), unbroken, no vignette; "
            "the first colour dominates the frame and the last appears only as "
            "the faintest tint, never as a mass" % ", ".join(colors)
        )
    else:
        background = (
            "ground derived from the brand palette (%s), unbroken, no vignette"
            % ", ".join(colors)
        )
    composition = _COMPOSITION[intent]

    subject = {
        "brand_name": brand_name or "the brand",
        "intent": intent,
        "archetype": gap.get("archetype") or "",
        "variant": gap.get("variant") or "",
        "slot": gap.get("slot") or "",
        "role": role,
        "lead": _LEAD[intent],
        "usage": _USAGE.get(role, _USAGE["decorative"]),
    }

    # Placeholders resolve from `subject` plus the two output fields the
    # pipeline folds in ({composition}, {background}). Every name used below is
    # present in one of those, so no placeholder can survive into the prompt.
    prompt = (
        "{lead} for the {archetype} section of {brand_name}'s website. "
        "{composition}. {background}. Calm, precise, editorial. {usage} "
        "It must depict no people, no products, no interfaces, no documents and "
        "no data of any kind."
    )

    reference = _reference(brand)
    job = {
        "schema_version": SCHEMA_VERSION,
        "id": _slug(gap.get("archetype"), gap.get("variant"), gap.get("slot"),
                    gap.get("section_uid")),
        "subject": subject,
        "spec": {
            "prompt_template": prompt,
            "negative": NEGATIVE_PROMPT,
        },
        "output": {
            "imgtype": _slug(gap.get("archetype"), gap.get("slot")),
            "aspect_ratio": gap.get("aspect") or "16:9",
            "resolution": "2k",
            "count": 1,
            "background": background,
            "composition": composition,
        },
        "engine": {
            "name": ENGINE_NAME,
            "model": MODEL_WITH_REFERENCE if reference else MODEL_TEXT_TO_IMAGE,
        },
    }
    if colors:
        job["output"]["colors"] = colors
    if reference is not None:
        job["reference"] = reference
    if not reference:
        job["engine"]["model_type"] = "standard"
    return job


# ── Motion: the same contract with a media_type ────────────────────────────
#
# `services/image-pipeline/core/job.schema.json` is extended in place to
# `job-v2` rather than forked (motion census §5). Forking is how the
# capture-bundle mistake repeats: two contracts for one thing, two loaders, and
# a cache that silently stops hitting because two implementations of one digest
# drifted apart.
#
# The extension is three additions and no removals:
#
#   * `media_type` — a DEFAULTING discriminator. Absent means image, so every
#     `job-v1` file on disk is already a valid v2 image job. Nothing migrates.
#   * `motion` — duration, dimensions, container, loop, and which engine.
#   * `remotion` — the composition, its entry, its props, their provenance and
#     the local font files.
#
# `job_hash` is untouched and needs to be: it digests the canonical JSON of the
# whole job minus `id`, so it already covers `remotion.props` — which carries the
# compiled token subset. Move the accent and the hash moves, so the cached render
# is invalidated, because the video should change. That property is what licenses
# a hash as a cache key, and the determinism run in the census (frames AND the
# muxed mp4 byte-identical across renders) is what licenses it for motion.


def media_type_of(job: dict) -> str:
    """The job's media type, DEFAULTED — never `job["media_type"]` directly.

    A v1 job has no such key and is an image job. Every consumer must read it
    through here, or the first `job["media_type"]` in a dispatch table turns
    every existing artefact into a KeyError and the back-compat guarantee into a
    docstring.
    """
    value = (job or {}).get("media_type")
    if value is None:
        return MEDIA_TYPE_IMAGE
    if value not in MEDIA_TYPES:
        raise ValueError(
            "unknown media_type %r — the discriminator is %s"
            % (value, list(MEDIA_TYPES)))
    return value


def is_motion(job: dict) -> bool:
    """True iff this job renders a moving image."""
    return media_type_of(job) == MEDIA_TYPE_VIDEO


def _props_provenance(props: dict) -> list:
    """`[{slot, field_key, source}]` for every rendered item in the props.

    Raises `PropsNotMeasured` on an item with no `field_key`, no `source`, or a
    `source` outside `VALID_PROPS_SOURCES`. The alternative — stamping
    `source: "default"`, or omitting the row — would put an unattributable string
    on a rendered frame, which is the content rule's failure mode in a medium
    where it is harder to see than in a `.tsx`.
    """
    items = props.get("items")
    if not isinstance(items, list) or not items:
        raise PropsNotMeasured(
            "props carry no items — a composition with nothing declared to "
            "render is not a job")
    out = []
    for i, item in enumerate(items):
        if not isinstance(item, dict):
            raise PropsNotMeasured("props item %d is not an object" % i)
        field_key = item.get("field_key")
        source = item.get("source")
        if not field_key:
            raise PropsNotMeasured(
                "props item %d (%r) names no field_key — it cannot be traced "
                "to a declaration" % (i, item.get("value")))
        if source not in VALID_PROPS_SOURCES:
            raise PropsNotMeasured(
                "props item %d has source %r; permitted sources are %s "
                "('default' is not one of them)"
                % (i, source, list(VALID_PROPS_SOURCES)))
        out.append({"slot": "items[%d].value" % i,
                    "field_key": str(field_key),
                    "source": source})
    return out


def _duration_frames(demand: dict, props: dict) -> int:
    """Frames in the render.

    Declared on the demand when the caller knows it; otherwise derived exactly
    the way `motion/src/Root.tsx` derives it — `introFrames + items *
    framesPerItem`. Derived rather than guessed, and by the same arithmetic as
    the composition, because a job that claims a different length than the
    composition renders produces a truncated or padded artefact under a hash
    that says it is correct.
    """
    declared = demand.get("duration_frames")
    if isinstance(declared, int) and declared >= 1:
        return declared
    intro = props.get("introFrames")
    per_item = props.get("framesPerItem")
    items = props.get("items")
    if all(isinstance(v, int) for v in (intro, per_item)) and isinstance(items, list):
        total = intro + len(items) * per_item
        if total >= 1:
            return total
    raise PropsNotMeasured(
        "duration is not measured: the demand declares no duration_frames and "
        "the props carry no introFrames/framesPerItem to derive it from")


def to_motion_job(demand: dict, props: dict) -> dict:
    """A motion demand + compiled props → one `job-v2` Remotion job.

    `demand` is the motion analogue of an `asset_resolver.art_demand()` row:
    `{section_uid, archetype, variant, slot, composition_id, entry,
      width, height, fps, container, loop}`.

    `props` is what `motion/tools/build_props.py` compiles — declared content
    with `field_key`/`source` on every item, plus the token subset read out of
    the build's own `globals.css`. It is passed in rather than compiled here:
    this module lowers, it does not read Supabase, and `build_props.py` already
    refuses (rather than defaults) when the declaration or the compiled tokens
    are unreachable.

    Raises `PropsNotMeasured` when the props carry no tokens, no traceable items
    or no derivable duration. There is no defaulting branch: an unmeasured
    design system must read as unmeasured.
    """
    demand = demand or {}
    props = dict(props or {})

    composition_id = str(demand.get("composition_id") or "").strip()
    entry = str(demand.get("entry") or "").strip()
    if not composition_id:
        raise ValueError("motion demand names no composition_id")
    if not entry:
        raise ValueError("motion demand names no entry (the registered root)")

    tokens = props.get("tokens")
    if not isinstance(tokens, dict) or not tokens:
        raise PropsNotMeasured(
            "props carry no tokens — motion cannot claim to read the page's "
            "design system when the page has not been compiled")

    provenance = _props_provenance(props)

    # The dimensions and frame rate live in exactly one place. A per-breakpoint
    # cut is a second job with the same composition_id and different width — so
    # the resolved values are written BACK into the props, which is what makes
    # the two cuts two hashes instead of two names for one cached file.
    width = int(demand.get("width") or props.get("width") or 0)
    height = int(demand.get("height") or props.get("height") or 0)
    fps = int(demand.get("fps") or props.get("fps") or 30)
    if width < 1 or height < 1:
        raise ValueError("motion demand/props carry no usable width/height")
    props["width"], props["height"], props["fps"] = width, height, fps

    duration_frames = _duration_frames(demand, props)

    container = str(demand.get("container") or "mp4")
    if container not in MOTION_CONTAINERS:
        raise ValueError("unknown container %r; the schema permits %s"
                         % (container, list(MOTION_CONTAINERS)))

    job = {
        "schema_version": SCHEMA_VERSION_MOTION,
        "media_type": MEDIA_TYPE_VIDEO,
        "id": _slug(composition_id, demand.get("slot"), demand.get("section_uid")),
        "motion": {
            "engine": ENGINE_REMOTION,
            "duration_frames": duration_frames,
            "fps": fps,
            "width": width,
            "height": height,
            "container": container,
            "loop": bool(demand.get("loop", False)),
        },
        "remotion": {
            "entry": entry,
            "composition_id": composition_id,
            "props": props,
            "props_provenance": provenance,
        },
    }
    fonts = [f for f in (demand.get("font_files") or props.get("font_files") or [])
             if isinstance(f, str) and f.strip()]
    if fonts:
        # Local paths only. A font fetched over the network is what breaks
        # portable determinism, which is the property the cache key rests on.
        remote = [f for f in fonts if f.strip().lower().startswith(("http://", "https://"))]
        if remote:
            raise ValueError(
                "font_files must be local paths; %s is a network dependency and "
                "breaks portable determinism" % remote[0])
        job["remotion"]["font_files"] = fonts
    return job


def to_generative_motion_job(gap: dict, brand: dict, duration_frames: int,
                             width: int, height: int, fps: int = 30,
                             container: str = "mp4", loop: bool = True) -> dict:
    """An atmospheric backdrop demand → one `job-v2` generative video job.

    This is the payoff of extending rather than forking: a generated backdrop is
    the existing image contract — same prompt, same negative prompt, same
    palette hint, same engine block — with `media_type: "video"` and a `motion`
    object. The generative path needed almost no new surface.

    Raises `EnginePolicyViolation` for anything that is not atmospheric. The
    reference's four atmospheric pieces are unbroken gradient fields behind an
    overlay, re-used twelve times; every other piece it ships is a named product
    demonstration with legible text, and those belong to Remotion.
    """
    intent = (gap.get("intent") or "").strip().lower()
    role = (gap.get("role") or "").strip().lower()
    if role != _ATMOSPHERIC_ROLE or intent not in _ATMOSPHERIC_INTENTS:
        raise EnginePolicyViolation(
            "engine 'generative' is atmospheric-backdrop only "
            "(role=%s intent in %s); this demand is role=%r intent=%r, which "
            "Remotion renders" % (_ATMOSPHERIC_ROLE,
                                  list(_ATMOSPHERIC_INTENTS), role, intent))
    if not isinstance(duration_frames, int) or duration_frames < 1:
        raise ValueError("duration_frames must be a positive integer")
    if int(width) < 1 or int(height) < 1:
        raise ValueError("width/height must be positive")
    if container not in MOTION_CONTAINERS:
        raise ValueError("unknown container %r" % container)

    job = to_job_v1(gap, brand)
    job["schema_version"] = SCHEMA_VERSION_MOTION
    job["media_type"] = MEDIA_TYPE_VIDEO
    job["motion"] = {
        "engine": ENGINE_GENERATIVE,
        "duration_frames": int(duration_frames),
        "fps": int(fps),
        "width": int(width),
        "height": int(height),
        "container": container,
        # True by default and recorded, not asserted: no catalogued model
        # advertises seamless looping, so a looping generative backdrop still
        # owes a loop-point pass. The flag is where that debt is visible.
        "loop": bool(loop),
    }
    return job


def lower_motion_demand(demand_rows, props_by_composition=None,
                        brand: dict = None) -> dict:
    """Every motion demand row → the distinct set of renders it asks for.

    Returns `{"jobs": [{job_hash, job, demands: [...]}], "refused": [...],
    "unlowered": [...]}` — the same three recorded outcomes, in the same shape,
    as `lower_gaps`. A caller that already consumes the image lowering consumes
    this one unchanged.

    Deduplicated by `job_hash`, so two sections asking for the same render share
    one file and one 5-second compute; a mobile cut of the same composition has
    different dimensions, therefore different props, therefore a different hash,
    therefore its own render — which is the desktop/mobile pattern the reference
    ships on every tab video.
    """
    props_by_composition = props_by_composition or {}
    jobs, index, refused, unlowered = [], {}, [], []
    for demand in demand_rows or []:
        engine = (demand.get("engine") or ENGINE_REMOTION).strip().lower()
        try:
            if engine == ENGINE_REMOTION:
                props = props_by_composition.get(demand.get("composition_id"))
                if props is None:
                    unlowered.append({
                        "demand": demand,
                        "reason": "no compiled props for composition %r — "
                                  "props are compiled out of band and a render "
                                  "is not invented from a name"
                                  % demand.get("composition_id"),
                    })
                    continue
                job = to_motion_job(demand, props)
            elif engine == ENGINE_GENERATIVE:
                job = to_generative_motion_job(
                    demand, brand or {},
                    duration_frames=demand.get("duration_frames") or 0,
                    width=demand.get("width") or 0,
                    height=demand.get("height") or 0,
                    fps=demand.get("fps") or 30,
                    container=demand.get("container") or "mp4",
                    loop=bool(demand.get("loop", True)))
            else:
                unlowered.append({"demand": demand,
                                  "reason": "unknown motion engine %r; the "
                                            "policy names %s"
                                            % (engine, [ENGINE_REMOTION,
                                                        ENGINE_GENERATIVE])})
                continue
        except (EnginePolicyViolation, ClaimBearingJob) as e:
            refused.append({"demand": demand, "reason": str(e)})
            continue
        except (PropsNotMeasured, UncompiledStyle, ValueError) as e:
            unlowered.append({"demand": demand, "reason": str(e)})
            continue
        h = job_hash(job)
        if h in index:
            index[h]["demands"].append(demand)
            continue
        entry = {"job_hash": h, "job": job, "demands": [demand]}
        index[h] = entry
        jobs.append(entry)
    return {"jobs": jobs, "refused": refused, "unlowered": unlowered}


def canonical_json(job: dict) -> str:
    """The exact bytes the hash is taken over. Sorted keys, no incidental
    whitespace, UTF-8 preserved — so two processes, two machines and two
    Python versions agree."""
    return json.dumps(job, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


#: Job fields that identify WHICH SECTION asked, not WHAT PICTURE was asked for.
#: Excluded from the hash — see `job_hash`.
_HASH_EXCLUDED_KEYS = ("id",)


def cache_key_json(job: dict) -> str:
    """`canonical_json` of the picture-determining part of a job.

    `id` carries the demanding section's `section_uid` so a generated file can
    be traced back to the artifact that asked for it. That is worth keeping —
    but it must not reach the hash, or two sections making the SAME request
    become two cache entries and two charges.

    Measured on cape-crypto: five HERO | centered sections each declare
    `slot=backdrop_url intent=texture aspect=16:9`. With `id` in the digest
    that is five hashes for five byte-identical prompts — five generations
    billed for one picture, in a module whose docstring promises the opposite.
    Excluding `id` collapses them to one.
    """
    return canonical_json({k: v for k, v in job.items()
                           if k not in _HASH_EXCLUDED_KEYS})


def job_hash(job: dict) -> str:
    """Content hash of a job spec — the cache key AND the determinism claim.

    SHA-256 over `cache_key_json`, truncated to 16 hex characters (64 bits;
    collision-implausible for a corpus of tens of jobs per tenant, and short
    enough to be a readable filename).

    Same declaration + same brand ⇒ same hash, WHEREVER it was declared ⇒
    generated once, cached, reused. Change the declaration or the palette and
    the hash moves, because the picture should.

    NEVER Python's builtin `hash()`: it is salted per process, so the same job
    would key a different cache entry every run and every generation would be
    re-billed. The capture filenames in this repo already shipped that bug once.
    """
    return hashlib.sha256(cache_key_json(job).encode("utf-8")).hexdigest()[:16]


# ── The brand: the COMPILED design system, and nothing else ────────────────
#
# `site-spec.json.style.palette` after `design_system.compile_style()` has run
# is the same dictionary `globals.css` is written from. It is therefore the
# only palette that describes the page a commissioned picture will sit on.
#
# The crawled palette lives in the same field BEFORE compilation (the compiler
# overwrites `site_spec["style"]` wholesale), which is exactly why this reads
# `design_source` rather than trusting the shape: the two are indistinguishable
# structurally and opposite in effect. For cape-crypto the crawl is a near-black
# ground with a `#00d18f` green; the compiled system is a white ground with a
# `#004e89` accent. A texture generated for the first, placed on the second,
# fights every section it appears in.

#: brand role -> compiled palette key. `surface` takes `bg_secondary` (the
#: tinted panel that actually appears on the page) rather than the `surface`
#: key, which in this build is a near-white barely distinct from the ground.
_BRAND_ROLE_FROM_PALETTE = (
    ("accent", "accent"),
    ("background", "bg_primary"),
    ("foreground", "text_primary"),
    ("surface", "bg_secondary"),
    ("surface_inverse", "surface_inverse"),
)


def brand_from_style(style: dict, name: str = "", reference_images=None) -> dict:
    """The brand dict `to_job_v1` takes, built from a COMPILED style.

    Raises `UncompiledStyle` when the style carries no design authority
    (`design_source` absent/empty) or no usable palette. Refusing is the point:
    the caller degrades to "no jobs, reason recorded", never to a guessed
    palette.
    """
    style = style or {}
    design_source = style.get("design_source")
    if not isinstance(design_source, str) or not design_source.strip():
        raise UncompiledStyle(
            "style carries no design_source — there is no compiled design "
            "system to generate against"
        )

    palette = style.get("palette") or {}
    brand = {"name": str(name or "").strip()}
    for role, key in _BRAND_ROLE_FROM_PALETTE:
        val = palette.get(key)
        if isinstance(val, str) and re.fullmatch(r"#[0-9a-fA-F]{3,8}", val.strip()):
            brand[role] = val.strip().lower()

    if not any(role in brand for role, _ in _BRAND_ROLE_FROM_PALETTE):
        raise UncompiledStyle(
            "compiled style has no usable palette hexes (%s)"
            % ", ".join(sorted(palette)) or "empty"
        )

    refs = [r for r in (reference_images or []) if isinstance(r, str) and r.strip()]
    if refs:
        brand["reference_images"] = refs
    return brand


def lower_gaps(gap_rows, brand: dict) -> dict:
    """Every gap row -> the distinct set of pictures it asks for.

    Returns `{"jobs": [{job_hash, job, demands: [...]}], "refused": [...],
    "unlowered": [...]}`.

    Three outcomes, all recorded, none silent:

    - **jobs** — a lowerable art demand, deduplicated by `job_hash`. The five
      HERO | centered sections on this site declare byte-identical backdrops;
      they collapse to one entry with five `demands`, so one picture is bought
      once. `demands` is what lets a cached file be placed back into all five.
    - **refused** — a claim-bearing declaration. `asset_resolver` already
      filters these before they become gaps; this is the second gate, and it
      writes a line rather than dropping one.
    - **unlowered** — a gap with no art intent, i.e. a FAILED FETCH
      (`reason: "no extracted source"`). The source had this image and we could
      not get it. That is retryable, and it is not a commission: generating a
      replacement for an image the source really has would substitute invented
      media for real media without saying so.

    Deterministic: entries come out in first-seen order and the digest ignores
    key order, so the same set of gaps always produces the same file.
    """
    jobs, index, refused, unlowered = [], {}, [], []
    for gap in gap_rows or []:
        intent = (gap.get("intent") or "").strip().lower()
        if not intent:
            unlowered.append({
                "gap": gap,
                "reason": "no art intent — a failed fetch is retried, not "
                          "commissioned",
            })
            continue
        try:
            job = to_job_v1(gap, brand)
        except ClaimBearingJob as e:
            refused.append({"gap": gap, "reason": "claim-bearing: %s" % e})
            continue
        except ValueError as e:
            unlowered.append({"gap": gap, "reason": str(e)})
            continue
        h = job_hash(job)
        if h in index:
            index[h]["demands"].append(gap)
            continue
        entry = {"job_hash": h, "job": job, "demands": [gap]}
        index[h] = entry
        jobs.append(entry)
    return {"jobs": jobs, "refused": refused, "unlowered": unlowered}
